default:
  tags:
    - master
  
variables:
    GIT_STRATEGY: none

stages:
  - update

job-updae:
  stage: update
  needs: []
  only:
   - main
  script:
    - cd ~/code/yumu-docs 
    - git pull 
    - npm i && npm run docs:build