name: update docs
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: update
        run: |
          cd ~/code/yumu-docs 
          git pull
          npm i && npm run docs:build
